# Stage 1: Build the Spring Boot application
FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

# Copy pom.xml first to improve Docker dependency caching
COPY pom.xml .

RUN mvn dependency:go-offline -B

# Copy source code
COPY src ./src

# Build the application
RUN mvn clean package -DskipTests


# Stage 2: Run the application
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

LABEL com.siemens.customerapi="customerapi"
LABEL version="1.0-SNAPSHOT"

COPY --from=build \
    /app/target/customerapi-0.0.1-SNAPSHOT.jar \
    customerapi.jar

EXPOSE 7074

ENTRYPOINT ["java", "-jar", "customerapi.jar"]